[solution]
name = "gdn-cuda-decode-col-v1"
definition = "gdn_decode_qk4_v8_d128_k_last"    # Benchmark definition name
author = "team"                                 # Team/author name

[build]
language = "python"                             # python | triton | cuda
entry_point = "msinfer_cuda.py::run"            # <file>::<symbol>
dependencies = []
destination_passing_style = true
